/*
================================================================================
P06_PROVIDER_READINESS.sql
================================================================================
STEP 6 (POST-PIPELINE) — PROVIDER DATA QUALITY READINESS STATS

PURPOSE:
  Computes per-column data quality metrics for the provider dataset and stores
  them in MDM.MASTER.DATA_READINESS_STATS. The readiness app reads this table
  directly — no calculations happen in the app at runtime.

RUN ON: COMPUTE_WH
INPUT:  MDM.TRANSFORMED.ALL_PROVIDERS_CLEAN (374,787 rows)
OUTPUT: Rows in MDM.MASTER.DATA_READINESS_STATS where ENTITY_TYPE = 'providers'

RUN AFTER: P01_provider_cleaning.sql (needs the clean table to exist)

METRICS COMPUTED PER COLUMN:
  - COMPLETENESS: % of records where the column is non-null and non-empty
  - UNIQUENESS: % of non-null values that are distinct (cardinality / count)
  - VALIDITY: % of non-null values that pass format validation rules
  - CONSISTENCY: % conforming to expected patterns (100% for clean columns)

COLUMNS ASSESSED:
  NPI, NAME_PRIMARY_CLEAN, ADDRESS_CLEAN, ZIP, PHONE,
  PROVIDER_TYPE_DESC, LICENSE_NUMBER, CITY, TAXONOMY_CODE, EMAIL

NOTES:
  - This should be re-run after any data refresh (new source data loaded)
  - The app computes SCORE = average of (completeness, uniqueness, validity, consistency)
  - Low-completeness columns (PHONE 30%, EMAIL 3%) are flagged as gaps in the UI
================================================================================
*/

USE WAREHOUSE COMPUTE_WH;
USE DATABASE MDM;
USE SCHEMA MASTER;

-- Create table if not exists
CREATE TABLE IF NOT EXISTS MDM.MASTER.DATA_READINESS_STATS (
    ENTITY_TYPE VARCHAR,
    SOURCE_TABLE VARCHAR,
    TOTAL_ROWS NUMBER,
    COLUMN_NAME VARCHAR,
    COMPLETENESS FLOAT,
    UNIQUENESS FLOAT,
    VALIDITY FLOAT,
    CONSISTENCY FLOAT
);

-- Remove old provider readiness stats
DELETE FROM MDM.MASTER.DATA_READINESS_STATS WHERE ENTITY_TYPE = 'providers';

-- Insert fresh stats
INSERT INTO MDM.MASTER.DATA_READINESS_STATS (ENTITY_TYPE, SOURCE_TABLE, TOTAL_ROWS, COLUMN_NAME, COMPLETENESS, UNIQUENESS, VALIDITY, CONSISTENCY)
SELECT 'providers', 'ALL_PROVIDERS_CLEAN', (SELECT COUNT(*) FROM MDM.TRANSFORMED.ALL_PROVIDERS_CLEAN), col.*
FROM (
    SELECT 'NPI' AS COLUMN_NAME,
        ROUND(100.0*SUM(CASE WHEN NPI IS NOT NULL AND NPI!='' THEN 1 ELSE 0 END)/COUNT(*),1) AS COMPLETENESS,
        ROUND(100.0*COUNT(DISTINCT NPI)/NULLIF(SUM(CASE WHEN NPI IS NOT NULL AND NPI!='' THEN 1 ELSE 0 END),0),1) AS UNIQUENESS,
        ROUND(100.0*SUM(CASE WHEN NPI_VALID=TRUE THEN 1 ELSE 0 END)/NULLIF(SUM(CASE WHEN NPI IS NOT NULL AND NPI!='' THEN 1 ELSE 0 END),0),1) AS VALIDITY,
        100.0 AS CONSISTENCY
    FROM MDM.TRANSFORMED.ALL_PROVIDERS_CLEAN

    UNION ALL SELECT 'NAME_PRIMARY_CLEAN',
        ROUND(100.0*SUM(CASE WHEN NAME_PRIMARY_CLEAN IS NOT NULL AND NAME_PRIMARY_CLEAN!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT NAME_PRIMARY_CLEAN)/NULLIF(SUM(CASE WHEN NAME_PRIMARY_CLEAN IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100, 100
    FROM MDM.TRANSFORMED.ALL_PROVIDERS_CLEAN

    UNION ALL SELECT 'ADDRESS_CLEAN',
        ROUND(100.0*SUM(CASE WHEN ADDRESS_CLEAN IS NOT NULL AND ADDRESS_CLEAN!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT ADDRESS_CLEAN)/NULLIF(SUM(CASE WHEN ADDRESS_CLEAN IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100, 100
    FROM MDM.TRANSFORMED.ALL_PROVIDERS_CLEAN

    UNION ALL SELECT 'ZIP',
        ROUND(100.0*SUM(CASE WHEN ZIP IS NOT NULL AND ZIP!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT ZIP)/NULLIF(SUM(CASE WHEN ZIP IS NOT NULL THEN 1 ELSE 0 END),0),1),
        ROUND(100.0*SUM(CASE WHEN LENGTH(ZIP)=5 THEN 1 ELSE 0 END)/NULLIF(SUM(CASE WHEN ZIP IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100
    FROM MDM.TRANSFORMED.ALL_PROVIDERS_CLEAN

    UNION ALL SELECT 'PHONE',
        ROUND(100.0*SUM(CASE WHEN PHONE IS NOT NULL AND PHONE!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT PHONE)/NULLIF(SUM(CASE WHEN PHONE IS NOT NULL THEN 1 ELSE 0 END),0),1),
        ROUND(100.0*SUM(CASE WHEN PHONE_VALID=TRUE THEN 1 ELSE 0 END)/NULLIF(SUM(CASE WHEN PHONE IS NOT NULL AND PHONE!='' THEN 1 ELSE 0 END),0),1),
        100
    FROM MDM.TRANSFORMED.ALL_PROVIDERS_CLEAN

    UNION ALL SELECT 'PROVIDER_TYPE_DESC',
        ROUND(100.0*SUM(CASE WHEN PROVIDER_TYPE_DESC IS NOT NULL AND PROVIDER_TYPE_DESC!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT PROVIDER_TYPE_DESC)/NULLIF(SUM(CASE WHEN PROVIDER_TYPE_DESC IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100, 100
    FROM MDM.TRANSFORMED.ALL_PROVIDERS_CLEAN

    UNION ALL SELECT 'LICENSE_NUMBER',
        ROUND(100.0*SUM(CASE WHEN LICENSE_NUMBER IS NOT NULL AND LICENSE_NUMBER!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT LICENSE_NUMBER)/NULLIF(SUM(CASE WHEN LICENSE_NUMBER IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100, 100
    FROM MDM.TRANSFORMED.ALL_PROVIDERS_CLEAN

    UNION ALL SELECT 'CITY',
        ROUND(100.0*SUM(CASE WHEN CITY IS NOT NULL AND CITY!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT CITY)/NULLIF(SUM(CASE WHEN CITY IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100, 100
    FROM MDM.TRANSFORMED.ALL_PROVIDERS_CLEAN

    UNION ALL SELECT 'TAXONOMY_CODE',
        ROUND(100.0*SUM(CASE WHEN TAXONOMY_CODE IS NOT NULL AND TAXONOMY_CODE!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT TAXONOMY_CODE)/NULLIF(SUM(CASE WHEN TAXONOMY_CODE IS NOT NULL THEN 1 ELSE 0 END),0),1),
        ROUND(100.0*SUM(CASE WHEN TAXONOMY_VALID='VALID_NUCC' THEN 1 ELSE 0 END)/NULLIF(SUM(CASE WHEN TAXONOMY_CODE IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100
    FROM MDM.TRANSFORMED.ALL_PROVIDERS_CLEAN

    UNION ALL SELECT 'EMAIL',
        ROUND(100.0*SUM(CASE WHEN EMAIL IS NOT NULL AND EMAIL!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        100, 100, 100
    FROM MDM.TRANSFORMED.ALL_PROVIDERS_CLEAN
) col;

-- Verify
SELECT COLUMN_NAME, COMPLETENESS, UNIQUENESS, VALIDITY, CONSISTENCY,
       ROUND((COMPLETENESS + UNIQUENESS + VALIDITY + CONSISTENCY) / 4.0, 1) AS OVERALL_SCORE
FROM MDM.MASTER.DATA_READINESS_STATS
WHERE ENTITY_TYPE = 'providers'
ORDER BY COMPLETENESS DESC;
