/*
================================================================================
R06_RECIPIENT_READINESS.sql
================================================================================
STEP 6 (POST-PIPELINE) — RECIPIENT DATA QUALITY READINESS STATS

PURPOSE:
  Computes per-column data quality metrics for the recipient dataset and stores
  them in MDM.MASTER.DATA_READINESS_STATS. The readiness app reads this table
  directly — no calculations happen in the app at runtime.

RUN ON: COMPUTE_WH
INPUT:  MDM.TRANSFORMED.ALL_RECIPIENTS_CLEAN (1,513 rows)
OUTPUT: Rows in MDM.MASTER.DATA_READINESS_STATS where ENTITY_TYPE = 'recipients'

RUN AFTER: R01_recipient_cleaning.sql (needs the clean table to exist)

METRICS COMPUTED PER COLUMN:
  - COMPLETENESS: % of records where the column is non-null and non-empty
  - UNIQUENESS: % of non-null values that are distinct (cardinality / count)
  - VALIDITY: % of non-null values that pass format validation rules
  - CONSISTENCY: % conforming to expected patterns (100% for clean columns)

COLUMNS ASSESSED:
  FIRST_NAME_CLEAN, LAST_NAME_CLEAN, SSN, DOB_CLEAN, ADDRESS_CLEAN,
  ADDRESS_ZIP, DRIVERS_LICENSE_NUMBER, PASSPORT_NUMBER

NOTES:
  - Re-run after any data refresh (new patient data loaded)
  - SSN validity = 9 digits; ZIP validity = 5 digits
  - Low completeness on ADDRESS_ZIP (52%) indicates many records lack ZIP
================================================================================
*/

USE WAREHOUSE COMPUTE_WH;
USE DATABASE MDM;
USE SCHEMA MASTER;

-- Ensure the table exists (created by P06 if providers ran first)
CREATE TABLE IF NOT EXISTS MDM.MASTER.DATA_READINESS_STATS (
    ENTITY_TYPE VARCHAR(20),
    SOURCE_TABLE VARCHAR(50),
    TOTAL_ROWS NUMBER,
    COLUMN_NAME VARCHAR(50),
    COMPLETENESS NUMBER(5,1),
    UNIQUENESS NUMBER(5,1),
    VALIDITY NUMBER(5,1),
    CONSISTENCY NUMBER(5,1)
);

-- Remove old recipient readiness stats
DELETE FROM MDM.MASTER.DATA_READINESS_STATS WHERE ENTITY_TYPE = 'recipients';

-- Insert fresh stats
INSERT INTO MDM.MASTER.DATA_READINESS_STATS (ENTITY_TYPE, SOURCE_TABLE, TOTAL_ROWS, COLUMN_NAME, COMPLETENESS, UNIQUENESS, VALIDITY, CONSISTENCY)
SELECT 'recipients', 'ALL_RECIPIENTS_CLEAN', (SELECT COUNT(*) FROM MDM.TRANSFORMED.ALL_RECIPIENTS_CLEAN), col.*
FROM (
    SELECT 'FIRST_NAME_CLEAN' AS COLUMN_NAME,
        ROUND(100.0*SUM(CASE WHEN FIRST_NAME_CLEAN IS NOT NULL AND FIRST_NAME_CLEAN!='' THEN 1 ELSE 0 END)/COUNT(*),1) AS COMPLETENESS,
        ROUND(100.0*COUNT(DISTINCT FIRST_NAME_CLEAN)/NULLIF(SUM(CASE WHEN FIRST_NAME_CLEAN IS NOT NULL THEN 1 ELSE 0 END),0),1) AS UNIQUENESS,
        100.0 AS VALIDITY, 100.0 AS CONSISTENCY
    FROM MDM.TRANSFORMED.ALL_RECIPIENTS_CLEAN

    UNION ALL SELECT 'LAST_NAME_CLEAN',
        ROUND(100.0*SUM(CASE WHEN LAST_NAME_CLEAN IS NOT NULL AND LAST_NAME_CLEAN!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT LAST_NAME_CLEAN)/NULLIF(SUM(CASE WHEN LAST_NAME_CLEAN IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100, 100
    FROM MDM.TRANSFORMED.ALL_RECIPIENTS_CLEAN

    UNION ALL SELECT 'SSN',
        ROUND(100.0*SUM(CASE WHEN SSN IS NOT NULL AND SSN!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT SSN)/NULLIF(SUM(CASE WHEN SSN IS NOT NULL THEN 1 ELSE 0 END),0),1),
        ROUND(100.0*SUM(CASE WHEN LENGTH(SSN)=9 THEN 1 ELSE 0 END)/NULLIF(SUM(CASE WHEN SSN IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100
    FROM MDM.TRANSFORMED.ALL_RECIPIENTS_CLEAN

    UNION ALL SELECT 'DOB_CLEAN',
        ROUND(100.0*SUM(CASE WHEN DOB_CLEAN IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT DOB_CLEAN)/NULLIF(SUM(CASE WHEN DOB_CLEAN IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100, 100
    FROM MDM.TRANSFORMED.ALL_RECIPIENTS_CLEAN

    UNION ALL SELECT 'ADDRESS_CLEAN',
        ROUND(100.0*SUM(CASE WHEN ADDRESS_CLEAN IS NOT NULL AND ADDRESS_CLEAN!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT ADDRESS_CLEAN)/NULLIF(SUM(CASE WHEN ADDRESS_CLEAN IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100, 100
    FROM MDM.TRANSFORMED.ALL_RECIPIENTS_CLEAN

    UNION ALL SELECT 'ADDRESS_ZIP',
        ROUND(100.0*SUM(CASE WHEN ADDRESS_ZIP IS NOT NULL AND ADDRESS_ZIP!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT ADDRESS_ZIP)/NULLIF(SUM(CASE WHEN ADDRESS_ZIP IS NOT NULL THEN 1 ELSE 0 END),0),1),
        ROUND(100.0*SUM(CASE WHEN LENGTH(ADDRESS_ZIP)=5 THEN 1 ELSE 0 END)/NULLIF(SUM(CASE WHEN ADDRESS_ZIP IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100
    FROM MDM.TRANSFORMED.ALL_RECIPIENTS_CLEAN

    UNION ALL SELECT 'DRIVERS_LICENSE_NUMBER',
        ROUND(100.0*SUM(CASE WHEN DRIVERS_LICENSE_NUMBER IS NOT NULL AND DRIVERS_LICENSE_NUMBER!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT DRIVERS_LICENSE_NUMBER)/NULLIF(SUM(CASE WHEN DRIVERS_LICENSE_NUMBER IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100, 100
    FROM MDM.TRANSFORMED.ALL_RECIPIENTS_CLEAN

    UNION ALL SELECT 'PASSPORT_NUMBER',
        ROUND(100.0*SUM(CASE WHEN PASSPORT_NUMBER IS NOT NULL AND PASSPORT_NUMBER!='' THEN 1 ELSE 0 END)/COUNT(*),1),
        ROUND(100.0*COUNT(DISTINCT PASSPORT_NUMBER)/NULLIF(SUM(CASE WHEN PASSPORT_NUMBER IS NOT NULL THEN 1 ELSE 0 END),0),1),
        100, 100
    FROM MDM.TRANSFORMED.ALL_RECIPIENTS_CLEAN
) col;

-- Verify
SELECT COLUMN_NAME, COMPLETENESS, UNIQUENESS, VALIDITY, CONSISTENCY,
       ROUND((COMPLETENESS + UNIQUENESS + VALIDITY + CONSISTENCY) / 4.0, 1) AS OVERALL_SCORE
FROM MDM.MASTER.DATA_READINESS_STATS
WHERE ENTITY_TYPE = 'recipients'
ORDER BY COMPLETENESS DESC;
